version: '3.8'

services:
  db1:
    image: postgres:16
    container_name: pg_db1
    environment:
      POSTGRES_USER: adelin
      POSTGRES_PASSWORD: padelin
      POSTGRES_DB: BankSystemID
    ports:
      - "6432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data
    restart: always

  db2:
    image: postgres:16
    container_name: pg_db2
    environment:
      POSTGRES_USER: adelin
      POSTGRES_PASSWORD: padelin
      POSTGRES_DB: BankSystemGE
    ports:
      - "6433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    restart: always

  db3:
    image: postgres:16
    container_name: pg_db3
    environment:
      POSTGRES_USER: adelin
      POSTGRES_PASSWORD: padelin
      POSTGRES_DB: BankSystemRU
    ports:
      - "6434:5432"
    volumes:
      - pgdata3:/var/lib/postgresql/data
    restart: always


  db4:
      image: postgres:16
      container_name: pg_db4
      environment:
        POSTGRES_USER: adelin
        POSTGRES_PASSWORD: padelin
        POSTGRES_DB: BankSystemFR
      ports:
        - "6435:5432"
      volumes:
        - pgdata4:/var/lib/postgresql/data
      restart: always

volumes:
  pgdata1:
  pgdata2:
  pgdata3:
  pgdata4: